### ISSUE TITLE
训练的模型如何调用

### ISSUE THREAD

**Issue by Doris1039** [I-Hope-Peace/DSMSCN#5]
作者您好，

我按照您的代码训练了模型，但是发现代码里面是保存的model.h5都是每一个epoch的选择后的h5文件。那我调用的时候是调用最后epoch产生的模型吗。想问下能分享一下用训练好的模型做变化检测的代码吗。谢谢了！

**Comment by ChenHongruixuan** [comment]
你好🙂你可以选择在验证集上精度最高的模型。用训练好的模型做变化检测的代码会在之后上传

**Comment by Doris1039** [comment]
> 你好🙂你可以选择在验证集上精度最高的模型。用训练好的模型做变化检测的代码会在之后上传

非常感谢！
